<?php
return [ 
    'credit_renews'=>
    [
        'renew_amount'=>[
            'lang' => 'np',
            'name_en' => 'Renew Amount',
            'name_np' => 'नविकरण रकम',
            'template_name' => 'RenewAmount',
            'key' => 'renew_amount',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_amount_words'=>[
            'lang' => 'np',
            'name_en' => 'Renew Amount Words',
            'name_np' => 'नविकरण रकम अक्षरुपि',
            'template_name' => 'RenewAmountWords',
            'key' => 'renew_amount_words',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_loan_interest_rate'=>[
            'lang' => 'np',
            'name_en' => 'Interest',
            'name_np' => 'व्याजदर',
            'template_name' => 'RenewInterest',
            'key' => 'renew_loan_interest_rate',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_loan_period'=>[
            'lang' => 'np',
            'name_en' => 'Loan Period',
            'name_np' => 'अबधि',
            'template_name' => 'RenewLoanPeriod',
            'key' => 'renew_loan_period',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_loan_period_type'=>[
            'lang' => 'np',
            'name_en' => 'Loan Period Type',
            'name_np' => 'बर्ष / महिना',
            'template_name' => 'RenewLoanPeriodType',
            'key' => 'renew_loan_period_type',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.loan_period_types',
            'required' => true,
            'required_if'=> false,

        ],
        'renew_decision_date'=>[
            'lang' => 'np',
            'name_en' => 'Renew Decision Date',
            'name_np' => 'नविकरण गर्ने निर्णय मिति',
            'template_name' => 'RenewDecisionDate',
            'key' => 'renew_decision_date',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_decision_date_bs'=>[
            'lang' => 'np',
            'name_en' => 'Renew Decision Date(BS)',
            'name_np' => 'नविकरण गर्ने निर्णय मिति',
            'template_name' => 'RenewDecisionDateBS',
            'key' => 'renew_decision_date_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_payment_amount'=>[
            'lang' => 'np',
            'name_en' => 'Renew Payment Amount',
            'name_np' => 'किस्ता भुक्तानी रकम',
            'template_name' => 'RenewPaymentAmount',
            'key' => 'renew_payment_amount',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_payment_amount_words'=>[
            'lang' => 'np',
            'name_en' => 'Renew Payment Amount Words',
            'name_np' => 'किस्ता भुक्तानी रकम अक्षरुपि',
            'template_name' => 'RenewPaymentAmountWords',
            'key' => 'renew_payment_amount_words',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'renew_payment_type'=>[
            'lang' => 'np',
            'name_en' => 'Renew Payment Type',
            'name_np' => 'किस्ता भुक्तानी तरिका',
            'template_name' => 'RenewPaymentType',
            'key' => 'renew_payment_type',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.payment_types',
            'required' => true,
            'required_if'=> false,
        ],  
    ],
];