<?php
return [ 
        'capacity'=>[
            'name_en' => 'Capacity to pay',
            'name_np' => 'तिर्न सक्ने क्षमता',
            'full_marks' => '50',
            'fields' => [
                'permanent_profession'=>[
                    'lang' => 'np',
                    'name_en' => 'Pernament Profession',
                    'name_np' => 'स्थायी पेशा (५ बर्ष भन्दा माथिको छ, ५ बर्ष भन्दा कमको छ, अल्पकालिन छ)',
                    'template_name' => 'PermanentProfession',
                    'key' => 'permanent_profession',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो', '3'=> 'ठिकै', '1'=>'कमजोर'],
                ],
                'income_regularity'=>[
                    'lang' => 'np',
                    'name_en' => 'Regularity of income source',
                    'name_np' => 'आम्दानीको स्रोतको नियमतिता (दैनिक / मासिक / बार्षिक)',
                    'template_name' => 'RegularityOfIncomeSource',
                    'key' => 'income_regularity',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'दैनिक', '3'=> 'मासिक', '1'=>'बार्षिक'],
                ],
                'income_loan_period_coordination'=>[
                    'lang' => 'np',
                    'name_en' => 'Coordination of income and loan installment period',
                    'name_np' => 'आम्दानी र ऋणको किस्ता अवधिसँग तालमेल (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'CoordinationOfIncomeAndLoanInstallementPeriod',
                    'key' => 'income_loan_period_coordination',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'business_loan_period_coordination'=>[
                    'lang' => 'np',
                    'name_en' => 'Coordination with occupation / business income and loan term',
                    'name_np' => 'पेशा/व्यवसायको आम्दानी र ऋणको अवधिसँग तालमेल (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'CoordinationWithBusinessIncomeAndLoanTerm',
                    'key' => 'business_loan_period_coordination',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'utility_of_loan'=>[
                    'lang' => 'np',
                    'name_en' => 'What is the utility of loan?',
                    'name_np' => 'ऋणको सदुपयोगिता कस्तो हुने देखिन्छ (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'UtilityOfLoan',
                    'key' => 'utility_of_loan',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'loan_utilization_earnings'=>[
                    'lang' => 'np',
                    'name_en' => 'Earnings due to good utilization of loans',
                    'name_np' => 'ऋणको सदुपयोगिताले कमाइको अवस्था (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'EarningDueToUtilizationOfLoan',
                    'key' => 'loan_utilization_earnings',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'economic_growth'=>[
                    'lang' => 'np',
                    'name_en' => 'Economic Growth',
                    'name_np' => 'व्यवसाय वृद्धि तथा आर्थिक अबस्थाको वृद्धि (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'EconomicGrowth',
                    'key' => 'economic_growth',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'business_market_condition'=>[
                    'lang' => 'np',
                    'name_en' => 'Business Market Condition',
                    'name_np' => 'व्यवसायको बजारको अवस्था (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'BusinessMarketCondition',
                    'key' => 'business_market_condition',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'other_sector_situation'=>[
                    'lang' => 'np',
                    'name_en' => 'The situation of getting loan from other sector',
                    'name_np' => 'अन्य क्षेत्रबाट ऋण प्राप्त गरेको अवस्था (छैन /ठिकै छ/ धेरै छ )',
                    'template_name' => 'OtherSectorSituation',
                    'key' => 'other_sector_situation',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'छैन', '3'=> 'ठिकै छ', '1'=>'धेरै छ'],
                ],
                'self_saving'=>[
                    'lang' => 'np',
                    'name_en' => 'State of self-savings in income and expenditure',
                    'name_np' => 'आम्दानी र खर्चमा खुद बचतको अवस्था (राम्रो छ/ठिक छ/सामान्य छ)',
                    'template_name' => 'SelfSavings',
                    'key' => 'self_saving',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['5'=>'राम्रो छ', '3'=> 'ठिक छ', '1'=>'सामान्य छ'],
                ],
                'capacity_total'=>[
                    'lang' => 'np',
                    'name_en' => 'Capacity To Pay',
                    'name_np' => 'तिर्न सक्ने क्षमता जम्मा',
                    'template_name' => 'CapacityTotal',
                    'key' => 'capacity_total',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => false,
                ],
            ],
        ],
        'character'=> [
            'name_en' => 'Character',
            'name_np' => 'चरित्र',
            'full_marks' => '30',
            'fields' => [
                'debt_collection_habits'=>[
                    'lang' => 'np',
                    'name_en' => 'Debt collection habits and records in the institution',
                    'name_np' => 'संस्थामा ऋण असुलीको बानी र अभिलेख (नियमित/ठीकै/सामान्य)',
                    'template_name' => 'DebtCollectionHabits',
                    'key' => 'debt_collection_habits',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'other_org_debt_paying_habits'=>[
                    'lang' => 'np',
                    'name_en' => 'Debt collection habits and records in the institution',
                    'name_np' => 'अन्य संघ संस्था को ऋण तिर्न बानी (राम्रो/ठीकै/थाहा छैन)',
                    'template_name' => 'DebtCollectionHabits',
                    'key' => 'other_org_debt_paying_habits',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'थाहा छैन'],
                ],
                'economic_behavior_society'=>[
                    'lang' => 'np',
                    'name_en' => 'Economic Behavior in Society',
                    'name_np' => 'समाजमा आर्थिक व्यवहार (राम्रो/ठीकै/सामान्य)',
                    'template_name' => 'EconomicBehaviorSociety',
                    'key' => 'economic_behavior_society',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'social_prestige'=>[
                    'lang' => 'np',
                    'name_en' => 'Social dignity and prestige',
                    'name_np' => 'समाजमा आर्थिक व्यवहार (राम्रो/ठीकै/सामान्य)',
                    'template_name' => 'SocialPrestige',
                    'key' => 'social_prestige',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'residential_status'=>[
                    'lang' => 'np',
                    'name_en' => 'Residential Status',
                    'name_np' => 'बसोवासको अवस्था (स्थायी रुपमा/अस्थायी/टाढा वस्छ)',
                    'template_name' => 'ResidentialStatus',
                    'key' => 'residential_status',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'स्थायी रुपमा', '2'=> 'अस्थायी', '1'=>'टाढा वस्छ'],
                ],
                'human_relation_in_society'=>[
                    'lang' => 'np',
                    'name_en' => 'Human relationship in home, family and society',
                    'name_np' => 'घर परिवार र समाजमा मानविय सम्बन्ध (राम्रो/ठिकै/सामान्य)',
                    'template_name' => 'HumanRelationInSociety',
                    'key' => 'human_relation_in_society',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'personal_moral_character'=>[
                    'lang' => 'np',
                    'name_en' => 'Personal Moral Character',
                    'name_np' => 'ब्यक्तिगत नैतिक चरित्रको अवस्था  (राम्रो/ठिकै/सामान्य)',
                    'template_name' => 'PersonalMoralCharacter',
                    'key' => 'personal_moral_character',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'state_of_eating'=>[
                    'lang' => 'np',
                    'name_en' => 'State of Eating and Drinking',
                    'name_np' => 'खान पानको अवस्था (असल/ठिकै/सामान्य)',
                    'template_name' => 'StateOfEating',
                    'key' => 'state_of_eating',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'fear_of_debt'=>[
                    'lang' => 'np',
                    'name_en' => 'Fear of debt',
                    'name_np' => 'ऋण संग डराउने अवस्था (डराउँछ/सामान्य डराउँछ/डराउँदैन)',
                    'template_name' => 'FearOfDebt',
                    'key' => 'fear_of_debt',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'डराउँछ', '2'=> 'सामान्य डराउँछ', '1'=>'डराउँदैन'],
                ],
                'state_of_economic_growth'=>[
                    'lang' => 'np',
                    'name_en' => 'State of Economic Growth',
                    'name_np' => 'आर्थिक रुपमा वृद्धिको अवस्था (राम्रो/ठिकै/सामान्य)',
                    'template_name' => 'StateOfEconomicGrowth',
                    'key' => 'state_of_economic_growth',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['3'=>'राम्रो', '2'=> 'ठिकै', '1'=>'सामान्य'],
                ],
                'character_total'=>[
                    'lang' => 'np',
                    'name_en' => 'Character',
                    'name_np' => 'चरित्र जम्मा',
                    'template_name' => 'CharacterTotal',
                    'key' => 'character_total',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => false,
                ],
            ],

        ],
        'collateral' =>[
            'name_en' => 'Collateral',
            'name_np' => 'धितो',
            'full_marks' => '10',
            'fields' => [
                'collateral_sell_condition'=>[
                    'lang' => 'np',
                    'name_en' => 'Condition to sell collateral',
                    'name_np' => 'धितो विक्री गर्न सक्ने अवस्था (सजिलैसँग/ठीकैसँग/सकिदैन)',
                    'template_name' => 'CollateralSellCondition',
                    'key' => 'collateral_sell_condition',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => ['2'=>'सजिलैसँग', '1'=> 'ठीकैसँग', '0.5'=>'सकिदैन'],
                ],
                'loan_amount_collateral_condition'=>[
                    'lang' => 'np',
                    'name_en' => 'The amount of loan and the condition of collateral value',
                    'name_np' => 'ऋणको परिमाण र धितो मुल्यको अवस्था (ऋण भन्दा धेरै/ठीकै/कम)',
                    'template_name' => 'LoanAmountAndCollateralCondition',
                    'key' => 'loan_amount_collateral_condition',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => ['2'=>'ऋण भन्दा धेरै', '1'=> 'ठीकै', '0.5'=>'कम'],
                ],
                'ownership_condition_collateral'=>[
                    'lang' => 'np',
                    'name_en' => 'The condition of ownership of the collateral',
                    'name_np' => 'धितोको स्वामित्वको अवस्था (ऋणी स्वयंको/परिवारको/अरुकै)',
                    'template_name' => 'OwnershipConditionOfCollateral',
                    'key' => 'ownership_condition_collateral',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => ['2'=>'ऋणी स्वयंको', '1'=> 'परिवारको', '0.5'=>'अरुकै'],
                ],
                'pledged_location'=>[
                    'lang' => 'np',
                    'name_en' => 'Pledged Location',
                    'name_np' => 'धितोको अवस्थिति  (सडक विजुलि भएको/सडक मात्र भएको/केहि नभएको)',
                    'template_name' => 'PledgedLocation',
                    'key' => 'pledged_location',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => ['2'=>'सडक विजुलि भएको', '1'=> 'सडक मात्र भएको', '0.5'=>'केहि नभएको'],
                ],
                'security_of_pledged'=>[
                    'lang' => 'np',
                    'name_en' => 'Condition and security of pledged land',
                    'name_np' => 'धितो जग्गाको अवस्था र सुरक्षा (सुरक्षित घडेरी/सुरक्षित खेती/खोला किनार)',
                    'template_name' => 'SecurityOfPledged',
                    'key' => 'security_of_pledged',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => ['2'=>'सुरक्षित घडेरी', '1'=> 'सुरक्षित खेती', '0.5'=>'खोला किनार'],
                ],
                'collateral_total'=>[
                    'lang' => 'np',
                    'name_en' => 'Collateral',
                    'name_np' => 'धितो जम्मा',
                    'template_name' => 'CollateralTotal',
                    'key' => 'collateral_total',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => false,
                    'required_if'=> false,
                    'option' => false,
                ],
            ],
        ],
        'capital_status'=>[
            'name_en' => 'Capital Status',
            'name_np' => 'पूँजी संरचना ',
            'full_marks' => '5',
            'fields' => [
                'regular_share_saving_status'=>[
                    'lang' => 'np',
                    'name_en' => 'Status of regular share savings',
                    'name_np' => 'नियमित रुपमा शेयर बचत प्राप्तीको अवस्था (नियमित/कहिले काँहि ढिलो /अनियमित)',
                    'template_name' => 'RegularShareSavingStatus',
                    'key' => 'regular_share_saving_status',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'नियमित', '0.5'=> 'कहिले काँहि ढिलो', '0.25'=>'अनियमित'],
                ],
                'growth_of_share_saving_in_institution'=>[
                    'lang' => 'np',
                    'name_en' => 'The state of growth of shares and savings in the institution',
                    'name_np' => 'संस्थामा शेयर र बचतको वृद्धिको अवस्था (राम्रो/ठीकै/स्थीर)',
                    'template_name' => 'GrowthOfShareAndShavingInInstitutaion',
                    'key' => 'growth_of_share_saving_in_institution',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'राम्रो', '0.5'=> 'ठीकै', '0.25'=>'स्थीर'],
                ],
                'cash_mobilization'=>[
                    'lang' => 'np',
                    'name_en' => 'Cash mobilization status',
                    'name_np' => 'नगद परिचालनको अवस्था (दैनिक/कहिलेकाँही/खेलाउदैन)',
                    'template_name' => 'CashMobilization',
                    'key' => 'cash_mobilization',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'दैनिक', '0.5'=> 'कहिलेकाँही', '0.25'=>'खेलाउदैन'],
                ],
                'debt_recovery_status'=>[
                    'lang' => 'np',
                    'name_en' => 'Debt recovery from personal property and income',
                    'name_np' => 'ब्यक्तिगत सम्पति र आम्दानीबाट ऋण असुलिको अवस्था (हुन सक्छ /सम्भावना छ/सक्दैन)',
                    'template_name' => 'DebtRecoveryStatus',
                    'key' => 'debt_recovery_status',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'हुन सक्छ ', '0.5'=> 'सम्भावना छ', '0.25'=>'सक्दैन'],
                ],
                'property_ownership'=>[
                    'lang' => 'np',
                    'name_en' => 'The state of ownership of the property',
                    'name_np' => 'सम्पतिको स्वामित्वको अवस्था (आफ्नै स्वामित्व/सँगोलको/छैन)',
                    'template_name' => 'PropertyOwnershipStatus',
                    'key' => 'property_ownership',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'आफ्नै स्वामित्व', '0.5'=> 'सँगोलको', '0.25'=>'छैन'],
                ],
                'capital_total'=>[
                    'lang' => 'np',
                    'name_en' => 'Capital Status',
                    'name_np' => 'पूँजी संरचना जम्मा',
                    'template_name' => 'CapitalTotal',
                    'key' => 'capital_total',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => false,
                ],
            ],
        ],
        'condition' =>[
            'name_en' => 'Condition',
            'name_np' => 'अवस्था  ',
            'full_marks' => '5',
            'fields' => [
                'weather_impact_on_business'=>[
                    'lang' => 'np',
                    'name_en' => 'Impact of weather on business',
                    'name_np' => 'मौसमले ब्यवसायमा पार्ने प्रभाव (पार्दैन/अलिअलि पार्छ/पुरै पार्छ)',
                    'template_name' => 'WeatherImpactOnBusiness',
                    'key' => 'weather_impact_on_business',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'पार्दैन', '0.5'=> 'अलिअलि पार्छ', '0.25'=>'पुरै पार्छ'],
                ],
                'disease_impact_on_business'=>[
                    'lang' => 'np',
                    'name_en' => 'Impact of disease on business',
                    'name_np' => 'रोग ब्याधीले व्यवसायमा पार्ने प्रभाव  (पार्दैन/अलिअलि पार्छ/पुरै पार्छ)',
                    'template_name' => 'DiseaseImpactOnBusiness',
                    'key' => 'disease_impact_on_business',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'पार्दैन', '0.5'=> 'अलिअलि पार्छ', '0.25'=>'पुरै पार्छ'],
                ],
                'legal_recognition_of_business'=>[
                    'lang' => 'np',
                    'name_en' => 'Legal recognition of business and profession',
                    'name_np' => 'व्यवसाय तथा पेशा को कानूनी मान्यता (कानुनी मान्यता छ/छैन/कानुन विपरित)',
                    'template_name' => 'LegalRecognitionOfBusiness',
                    'key' => 'legal_recognition_of_business',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'कानुनी मान्यता छ', '0.5'=> 'छैन', '0.25'=>'कानुन विपरित'],
                ],
                'environment_impact_on_business'=>[
                    'lang' => 'np',
                    'name_en' => 'Environmental Impact on Business and Work',
                    'name_np' => 'व्यावसाय तथा कामको वातावरणीय प्रभाव (पर्दैन/अलिअलि/अत्याधिक)',
                    'template_name' => 'EnvironmentalImpactOnBusiness',
                    'key' => 'environment_impact_on_business',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'पर्दैन', '0.5'=> 'अलिअलि', '0.25'=>'अत्याधिक'],
                ],
                'impact_of_profession_on_members'=>[
                    'lang' => 'np',
                    'name_en' => 'Impact of the profession / profession on the members themselves',
                    'name_np' => 'व्यासाय/पेशाले सदस्य स्वयंलाई पार्ने प्रभाव (पार्दैन/अलिअलि/अत्याधिक) ',
                    'template_name' => 'ImpactOfProfessionOnMember',
                    'key' => 'impact_of_profession_on_members',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => ['1'=>'पार्दैन', '0.5'=> 'अलिअलि', '0.25'=>'अत्याधिक'],
                ],
                'condition_total'=>[
                    'lang' => 'np',
                    'name_en' => 'Condition Status',
                    'name_np' => 'अवस्था जम्मा',
                    'template_name' => 'ConditionTotal',
                    'key' => 'condition_total',
                    'foreign_key' =>false,
                    'type' => 'number',
                    'config' => false,
                    'required' => true,
                    'required_if'=> false,
                    'option' => false,
                ],
            ],
        ],
    ];