<?php

return [
	'realpath' => realpath(__DIR__),
	'api_base_url' => env('API_BASE_URL', 'https://ssf.gov.np'),
	'activity_log' => env('ACTIVITY_LOG', true),

	'show_recaptcha' => env('RECAPTCHA_ENABLE', true),

    'mail_to'      => env('MAIL_TO', 'info@vtechnepal.com'),
    'mail_to_name' => env('MAIL_TO_NAME', 'Sahakari Docs'),

	'format' => [
            'date' => 'M d, Y',
            'datetime' => 'M d, Y h:i A',
            'dateInForm' => 'Y-m-d',
        ],
	'gender' => [
		'male' => 'पुरुष',
		'female' => 'महिला',
		'others' => 'अन्य',
	],

	'suggestion_types' => [
		'applicant' => 'आबेदक',
		'guarantor' => 'धनजमानी',
		'land_lander' => 'जग्गा धितो दिने',
	],

	'record_types' => [
		'darta' => 'दर्ता',
		'chalani' => 'चलानी',
	],

	'fiscal_year' => [
		'079-080' => '०७९/०८०',
		'080-081' => '०८०/०८१',
		'081-082' => '०८१/०८२',
		'082-083' => '०८२/०८३',
		'083-084' => '०८३/०८४',
		'084-085' => '०८४/०८५',
	],

	'marital_status' => [
        '1' => 'विवाहित',
        '2' => 'अविवाहित',
        '3' => 'विदुर',
        '4' => 'विदुवा',
        '5' => 'परपाचुके',
        '6' => 'छुट्टिएको',
    ],

	'caste_code' => [
        '1' =>	"क्षेत्री",
		'2' =>	"ब्रामण",
		'3' =>	"मगर",
		'4' =>	"थारु",
		'5' =>	"तमाङ्ग",
		'6' =>	"नेवार",
		'7' =>	"मुसलमान",
		'8' =>	"कामी",
		'9' =>	"यादव",
		'10' =>	"राई",
		'11' =>	"गुरुङ्ग",
		'12' =>	"दमाई/धोली",
		'13' =>	"लिम्वु",
		'14' =>	"ठकुरी ",
		'15' =>	"सार्की",
		'16' =>	"तेली",
		'17' =>	"चमार/हरिजन/राम",
		'18' =>	"कोईरी",
		'19' =>	"कुर्मी",
		'20' =>	"सन्यासी/दसनामी",
		'21' =>	"धानुक",
		'22' =>	"मुसहर",
		'23' =>	"दुसाध/पासवान/पासी",
		'24' =>	"शेर्पा",
		'25' =>	"सोनार",
		'26' =>	"केवट",
		'27' =>	"ब्रामण तराइ",
		'28' =>	"कथवानिया",
		'29' =>	"घर्ति/भुजेल",
		'30' =>	"मलाल्स",
		'31' =>	"कलवार",
		'32' =>	"कुमाल",
		'33' =>	"हजाम/ठाकुर",
		'34' =>	"कानु",
		'35' =>	"राजवशीं",
		'36' =>	"सुनुवार",
		'37' =>	"सुधी",
		'38' =>	"लोसार",
		'39' =>	"तत्मा/तत्वा",
		'40' =>	"खत्वे",
		'41' =>	"धोवी",
		'42' =>	"माझी",
		'43' =>	"नुनिया",
		'44' =>	"गुप्ता",
		'45' =>	"अन्य",
    ],

	'loan_period_types' => ['year' => 'वर्ष', 'month'=>'महिना'],

	'status' => [
		'active' => 'Active',
		'inactive' => 'Inactive',
	],

	'application_status' => [
		'new' => 'New',
		'edited' => 'Edited',
		'reviewed' => 'Reviewed',
		'approved' => 'Approved',
		'duplicate' => 'Duplicate',
		'hold' => 'On Hold',
		'invalid' => 'Invalid',
		'declined' => 'Declined',
	],

	'reviewer_status' => [
		// 'new' => 'New',
		'reviewed' => 'Reviewed',
		// 'approved' => 'Approved',
		// 'duplicate' => 'Duplicate',
		'hold' => 'On Hold',
		'invalid' => 'Invalid',
		// 'declined' => 'Declined',
	],

	'approver_status' => [
		// 'new' => 'New',
		// 'reviewed' => 'Reviewed',
		'approved' => 'Approved',
		'duplicate' => 'Duplicate',
		'hold' => 'On Hold',
		// 'invalid' => 'Invalid',
		'declined' => 'Declined',
	],

	'application_status_details' => [
		'new' => [
					'name_en' => 'New',
					'name_np' => 'नयाँ ',
					'color' => 'info',
					'icon'  => 'fa fa-plus',
				],
		'edited' => [
					'name_en' => 'Edited',
					'name_np' => 'सम्पादित',
					'color' => 'danger',
					'icon'  => 'fi fi-pencil',
				],
		'reviewed' => [
				'name_en' => 'Reviewed',
				'name_np' => 'समीक्षा गरिएको',
				'color' => 'primary',
				'icon'  => 'fi fi-eye',
			],

		'approved' => [
					'name_en' => 'Approved',
					'name_np' => 'प्रमाणीकरण गरिएको',
					'color' => 'success',
					'icon'  => 'fi fi-shield-ok',
				],
		'hold' => [
					'name_en' => 'On Hold',
					'name_np' => 'केहि समय रोकिएको',
					'color' => 'warning',
					'icon'  => 'fi fi-circle-spin',
				],
		'duplicate' => [
					'name_en' => 'Duplicate',
					'name_np' => 'अनुलिपि',
					'color' => 'danger',
					'icon'  => 'fi fi-loading',
				],
		'invalid' => [
					'name_en' => 'Invalid',
					'name_np' => 'अशुद्ध भएको',
					'color' => 'warning',
					'icon'  => 'fi fi-go-back',
				],
		'declined' => [
					'name_en' => 'Declined',
					'name_np' => 'रद्द गरिएको',
					'color' => 'danger',
					'icon'  => 'fi fi-close',
				],
	],

	'allowedDocExtension' => ['JPG','JPEG','jpg','jpeg', 'pdf', 'PDF'],
	'filesize' => '200k',

	'template_folder' => [
        '1_office_internal' => 'आन्तरिक कागजात',
		'2_all' => 'अनिवार्य कागजात',
		'3_general' => 'सामुहिक जमानी ऋण',
		'3_home' => 'घर जग्गा धितो ऋण',
        '3_vehicle' => 'सबारी साधन धितो ऋण',
        '3_periodic' => 'आवधिक बचत धितो ऋण',
        '3_microfinance' => 'महिला लघुबित्त ऋण',
        '4_taketa_patras' => 'ताकेता पत्र',
		'5_credit_analysis' => 'ऋण अनुसन्धान कागजात',
        '6_extra' => 'अतिरिक्त कागजात',
		'7_taketa_notices' => 'ताकेता सुचनाहरु',
		'8_general_maag_aabedan' => 'सामुहिक जमानी माग / आवेदन फारम',
		'8_home_maag_aabedan' => 'घर जग्गा धितो माग / आवेदन फारम',
		'8_vehicle_maag_aabedan' => 'सबारी साधन धितो माग / आवेदन फारम',
		'8_periodic_maag_aabedan' => 'आवधिक बचत धितो माग / आवेदन फारम',
		'8_microfinance_maag_aabedan' => 'महिला लघुबित्त माग / आवेदन फारम',
		'9_credit_renews' => 'ऋण नविकरण कागजात',
		'10_mortgage_appraisals' => 'धितो मूल्याङ्कन कागजात',
	], 
	
	'form_tabs' => [
		'applicant_details' => 'आबेदक विवरण',
		'collateral_details' => 'धितो विवरण',
		'loan_details' => 'ऋण विवरण',
		'guarantor_details' => 'धनजमानी विवरण',
        'sanchi_details' => 'साक्षी विवरण ',
        'other_details' => 'अन्य',
        'review' => 'प्रमाणित',
	],
	'mortgage_appraisal' => [
		'home_land' => 'घर जग्गा',
		'land' => 'जग्गा',
	],


	'loan_types' => [
        'general' => 'सामुहिक जमानी ऋण',
		'home' => 'घर जग्गा धितो ऋण',
        'vehicle' => 'सबारी साधन धितो ऋण',
        'periodic' => 'आवधिक बचत धितो ऋण',
        'microfinance' => 'महिला लघुबित्त  ऋण',
	],
	'payment_types' => [
        'daily' => 'दैनिक',
        'half_month' => 'अर्धमासिक',
		'month' => 'मासिक',
        'quater' => 'त्रैमासिक',
        'half_year' => 'अर्धबार्षिक',
        'year' => 'बार्षिक',
        'never' => 'एकमुष्ठ',
	],
	'land_units' =>
	[
		'aana' => 'आना',
		'haat' => 'हात',
		'ropani' => 'रोपनी',
		'sqmeter' => 'वर्ग मिटर',
		'sqfeet' => 'वर्ग फिट',
		'bigha' => 'विघा',
		'dhur' => 'धुर',
		'kattha' => 'कठ्ठा',
	],

	'letter_type' => [
		'first' => 'पहिलो पत्र',
		'second' => 'दोश्रो पत्र',
		'third' => 'तेश्रो पत्र',
		'last' => 'अन्तिम पत्र',
	],

	'academic_levels' => [
		'normal' => 'सामा‍न्य',
		'see' => 'एस एल सी / एस ई ई',
		'intermediate' => '10+2',
		'bachelor' => 'स्नातक',
		'master' => 'स्नातकोत्तर',
	],
	'relations' => [
		'mother'  => 'आमा',
		'uncle'  => 'काका',
		'aunt'  => 'काकी',
		'son'  => 'छोरा',
		'daughter'  => 'छोरी',
		'son_in_law'  => 'ज्वाई',
		'elder_brother'  => 'दाजु',
		'elder_sister'  => 'दिदि',
		'grand_daughter'  => 'नातिनी',
		'grand_son'  => 'नाती',
		'wife'  => 'पत्नि',
		'husband'  => 'पति',
		'daughter_in_law'  => 'बुहारी',
		'younger_sister'  => 'बहिनी',
		'grand_father'  => 'बाजे',
		'father'  => 'बाबु',
		'younger_brother'  => 'भाई',
		'brother_in_law'  => 'भिनाजु',
		'neighbor'=>'छिमेकि',
		'relative'=>'आफन्त',
		'nephew'=>'भान्जा',
		'niece'=>'भान्जी',
		'friend'=>'साथी',
		'self'		=> 'स्वयम्',
	],
	'occupations' => [
			'farmer' => 'कृषक',
			'job' => 'नोकरी',
			'foreign_employment' => 'वैदेशीक रोजगार',
			'social_worker' => 'समाजसेवी',
			'business' => 'व्यापार/व्यवसायी',
			'pension' => 'पेन्सन',
	],

	'office_fields'=>
	[
		'name_en'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Name English',
			'name_np' => 'सहकारीको नाम अंग्रेजी',
			'template_name' => 'SahakariNameEn',
			'key' => 'name_en',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'name_np'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Name Nepali',
			'name_np' => 'सहकारीको नाम नेपालि',
			'template_name' => 'SahakariNameNP',
			'key' => 'name_np',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'register_nikaye'=>[
			'lang' => 'np',
			'name_en' => 'Register Nikaye',
			'name_np' => 'दर्ता निकाए',
			'template_name' => 'RegisterNikaye',
			'key' => 'register_nikaye',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'head_office'=>[
			'lang' => 'np',
			'name_en' => 'Head Office',
			'name_np' => 'प्रधान कार्यालय',
			'template_name' => 'HeadOffice',
			'key' => 'head_office',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => false,
			'required_if'=> false,
		],
		'registration_number'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Registration Number',
			'name_np' => 'सहकारीको दर्ता नं',
			'template_name' => 'SahakariDartaNo',
			'key' => 'registration_number',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'registration_date'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Registration Date',
			'name_np' => 'सहकारीको दर्ता मिति',
			'template_name' => 'SahakariDartaDate',
			'key' => 'registration_date',
			'foreign_key' =>false,
			'type' => 'datetime',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'registration_date_bs'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Registration Date(BS)',
			'name_np' => 'सहकारीको दर्ता मिति',
			'template_name' => 'SahakariDartaDateBS',
			'key' => 'registration_date_bs',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'province'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Address Province',
			'name_np' => 'सहकारी रहेको प्रदेश',
			'template_name' => 'SAddressProvince',
			'key' => 'province',
			'foreign_key' =>'province',
			'type' => 'number',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'district'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Address District',
			'name_np' => 'सहकारी रहेको जिल्ला',
			'template_name' => 'SAddressDistrict',
			'key' => 'district',
			'foreign_key' =>'district',
			'type' => 'number',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'localgovt'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Address Local Govt',
			'name_np' => 'सहकारी रहेको स्थानिय तह',
			'template_name' => 'SAddressLocalGovt',
			'key' => 'localgovt',
			'foreign_key' =>'localgovt',
			'type' => 'number',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'ward'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Address Ward',
			'name_np' => 'सहकारी रहेको वडा',
			'template_name' => 'SAddressWard',
			'key' => 'ward',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'tole'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Address Tole',
			'name_np' => 'सहकारी रहेको टोल',
			'template_name' => 'SAddressTole',
			'key' => 'tole',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'former_address'=>[
            'lang' => 'np',
			'name_en' => ' Former Address',
            'name_np' => 'साबिक ठेगाना',
            'template_name' => 'FormerAddress',
            'key' => 'former_address',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ], 
		'president_name'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative President Name',
			'name_np' => 'सहकारीको अध्यक्षको नाम',
			'template_name' => 'SahakariPresidentName',
			'key' => 'president_name',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'manager_name'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Manager/CEO',
			'name_np' => 'सहकारीको व्यवस्थापक / CEO',
			'template_name' => 'SahakariManagerCEO',
			'key' => 'manager_name',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false, 
		],
		'phone'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Phone',
			'name_np' => 'सहकारीको फोन',
			'template_name' => 'SahakariPhone',
			'key' => 'phone',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false, 
		],
		'email'=>[
			'lang' => 'en',
			'name_en' => 'Cooperative Email',
			'name_np' => 'सहकारीको ईमेल',
			'template_name' => 'SahakariEmail',
			'key' => 'email',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false, 
		],

		'expiration_date'=>[
			'lang' => 'np',
			'name_en' => 'Expiration Date',
			'name_np' => 'म्याद समाप्त हुने मिति',
			'template_name' => 'ExpirationDate',
			'key' => 'expiration_date',
			'foreign_key' =>false,
			'type' => 'datetime',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'expiration_date_bs'=>[
			'lang' => 'np',
			'name_en' => 'Expiration Date(BS)',
			'name_np' => 'म्याद समाप्त हुने मिति',
			'template_name' => 'ExpirationDateBS',
			'key' => 'expiration_date_bs',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],

		'vice_president_name'=>[
			'lang' => 'np',
			'name_en' => 'Vice President Name',
			'name_np' => 'सहकारीको उपाध्यक्षको नाम',
			'template_name' => 'SahakariVicePresidentName',
			'key' => 'vice_president_name',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'secretary'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Secretary Name',
			'name_np' => 'सहकारीको सचिबको नाम',
			'template_name' => 'SahakariSecretaryName',
			'key' => 'secretary',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'treasurer'=>[
			'lang' => 'np',
			'name_en' => 'Cooperative Treasurer Name',
			'name_np' => 'सहकारीको कोषाध्यक्षको नाम',
			'template_name' => 'SahakariTreasurerName',
			'key' => 'treasurer',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'loan_coordinator'=>[
			'lang' => 'np',
			'name_en' => 'Loan Coordinator Name',
			'name_np' => 'ऋण संयोजकको नाम',
			'template_name' => 'LoanCoordinatorName',
			'key' => 'loan_coordinator',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'loan_member_1'=>[
			'lang' => 'np',
			'name_en' => 'Loan Member Name (1)',
			'name_np' => 'ऋण सदस्यको नाम (१)',
			'template_name' => 'LoanMember1Name',
			'key' => 'loan_member_1',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'loan_member_2'=>[
			'lang' => 'np',
			'name_en' => 'Loan Member Name (2)',
			'name_np' => 'ऋण सदस्यको नाम (२)',
			'template_name' => 'LoanMember2Name',
			'key' => 'loan_member_2',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => true,
			'required_if'=> false,
		],
		'slogan'=>[
			'lang' => 'np',
			'name_en' => 'Slogan',
			'name_np' => 'नारा',
			'template_name' => 'Slogan',
			'key' => 'slogan',
			'foreign_key' =>false,
			'type' => 'string',
			'config' => false,
			'required' => false,
			'required_if'=> false,
		],


	],


	'province_raw_names' => 
	[
		'province_1' => ['province 1', 'Province 1'],
		'province_2' => ['province 2', 'Province 2'],
		'province_3' => ['province 3', 'Province 3', 'Bagmati Province'],
		'province_4' => ['province 4', 'Province 4', 'Gandaki Province'],
		'province_5' => ['province 5', 'Province 5', 'Lumbini Province'],
		'province_6' => ['province 6', 'Province 6', 'Karnali Province'],
		'province_7' => ['province 7', 'Province 7', 'Sudur Pascim Province', 'Sudur Pashchim Province', 'Sudurpashchim Province', 'Sudurpashchim'],
	],

    'panel_permission' => [
		'Application' => [
			'panel_name' => 'Application',
			'actions' => ['create', 'update', 'show', 'delete', 'download', 'restore', 'forceDelete'],
			],
		'Templates' => [
			'panel_name' => 'Templates',
			'actions' => ['create', 'download', 'show', 'delete'],
			],
		'Offices' => [
			'panel_name' => 'Offices',
			'actions' => ['create', 'update', 'show', 'delete', 'restore', 'forceDelete'],
			],
		'Users' => [
			'panel_name' => 'Users',
			'actions' => ['create', 'update', 'show', 'delete', 'restore', 'forceDelete'],
			],
		'Role' => [
			'panel_name' => 'Role',
			'actions' => ['create', 'update', 'show', 'delete'],
			],
		'Site Configuration' => [
			'panel_name' => 'Site Configuration',
			'actions' => ['update'],
			],
			
	],
	'wards' => [
		1=>'१',
		1=>"१",
		2=>"२",
		3=>"३",
		4=>"४",
		5=>"५",
		6=>"६",
		7=>"७",
		8=>"८",
		9=>"९",
		10=>"१०",
		11=>"११",
		12=>"१२",
		13=>"१३",
		14=>"१४",
		15=>"१५",
		16=>"१६",
		17=>"१७",
		18=>"१८",
		19=>"१९",
		20=>"२०",
		21=>"२१",
		22=>"२२",
		23=>"२३",
		24=>"२४",
		25=>"२५",
		26=>"२६",
		27=>"२७",
		28=>"२८",
		29=>"२९",
		30=>"३०",
		31=>"३१",
		32=>"३२",
		33=>"३३",
	],

	'blacklist_import_head' => 
	[
		'black_list_no' => ['BLACKLIST NO.', 'Blacklist no.','BLACKLIST NO.'],
		'black_list_date'   => ['BLACKLIST DATE', 'blacklist date', 'Blacklist Date'],
		'borrower_name' => ['BORROWER NAME', 'Borrower name'],
		'associated_person_or_firm' => ['ASSOCIATED PERSON & FIRM /COMPANIES', 'Associated Person and Firm/Companies',],
	],

	'application_export_fields'=>[
		'subscription_id' => 'MembershipNumber',
		'borrower_name' => 'Name',
		'borrower_name_en' => 'NameinEnglish',
		'subscription_date_bs' => 'MembershipDateNepali',
		'borrower_gender' => 'GenderRecord',
		'b_dob_bs' => 'DOBNepali',
		'b_grand_father_name' => 'GrandFatherName',
		'b_father_name' => 'FatherOrHusbandName',
		'b_marital_status' => 'MartialStatusStr',
		'citizenship_number' => 'CitizenshipNo',
		'citizenship_issue_date_bs' => 'IssuedDateNepali',
		'citizenship_issue_district' => 'IssuedDistrictId',
		'b_caste_code' => 'CastRecordId',
		'address' => 'Address',
		'share_certificate_number' => 'ShareCertificateNo',
		'share_amount' => 'TotalShare',

	],
];
