<?php

return [
    'applicant_details' => [
   
        'borrower_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Name',
            'name_np' => 'ऋण लिने को पुरा नाम',
            'template_name' => 'BorrowerName',
            'key' => 'borrower_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,

        ],
        'borrower_name_en'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Name English',
            'name_np' => 'ऋण लिने को पुरा नाम अंग्रेजी',
            'template_name' => 'BorrowerNameEn',
            'key' => 'borrower_name_en',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,

        ],
        'borrower_gender'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Gender',
            'name_np' => 'लिंग',
            'template_name' => 'BorrowerGender',
            'key' => 'borrower_gender',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.gender',
            'required' => true,
            'required_if'=> false,
        ],
        'b_dob'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Date of Birth',
            'name_np' => 'जन्म मिति',
            'template_name' => 'BorrowerDateofBirth',
            'key' => 'b_dob',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_dob_bs'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Date of Birth (BS)',
            'name_np' => 'जन्म मिति',
            'template_name' => 'BorrowerDateofBirthBS',
            'key' => 'b_dob_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_age'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Age',
            'name_np' => 'उमेर',
            'template_name' => 'BorrowerAge',
            'key' => 'b_age',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],

        'b_grand_father_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Grand Father Name',
            'name_np' => 'बाजे/ससुराको नाम',
            'template_name' => 'BorrowerGrandFatherName',
            'key' => 'b_grand_father_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_father_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Father Name',
            'name_np' => 'बाबु/पतिको नाम',
            'template_name' => 'BorrowerFatherName',
            'key' => 'b_father_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_mother_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Mother Name',
            'name_np' => 'सासु/आमाको नाम',
            'template_name' => 'BorrowerMotherName',
            'key' => 'b_mother_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
        'b_spouse_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Spouse Name',
            'name_np' => 'श्रीमान / श्रीमती को नाम',
            'template_name' => 'BorrowerSpouseName',
            'key' => 'b_spouse_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
        'b_son_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Son(s) Name',
            'name_np' => 'छोरा(हरु)को नाम',
            'template_name' => 'BorrowerSonName',
            'key' => 'b_son_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
        'b_daughter_name'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Daughter(s) Name',
            'name_np' => 'छोरी(हरु)को नाम',
            'template_name' => 'BorrowerDaughterName',
            'key' => 'b_daughter_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],

        'b_edu_qualification'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Education Qualification',
            'name_np' => 'शौक्षिक योग्यता',
            'template_name' => 'BorrowerEduQualification',
            'key' => 'b_edu_qualification',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.academic_levels',
            'required' => false,
            'required_if'=> false,
        ],
        'b_caste_code'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Caste',
            'name_np' => 'जात',
            'template_name' => 'BorrowerCaste',
            'key' => 'b_caste_code',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.caste_code',
            'required' => false,
            'required_if'=> false,
        ],
        'b_marital_status'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Marital Status',
            'name_np' => 'वैवाहिक स्थिती',
            'template_name' => 'BorrowerMaritalStatus',
            'key' => 'b_marital_status',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.marital_status',
            'required' => false,
            'required_if'=> false,
        ],

        'b_occupation'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Occupation',
            'name_np' => 'पेशा / व्यवसाय',
            'template_name' => 'BorrowerOccupation',
            'key' => 'b_occupation',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.occupations',
            'required' => false,
            'required_if'=> false,
        ],
        'b_occupation_location'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Occupation Location',
            'name_np' => 'पेशा / व्यवसायको नाम र स्थान',
            'template_name' => 'BorrowerOccupationLocation',
            'key' => 'b_occupation_location',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],


        'b_p_province'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Permanent Province',
            'name_np' => 'प्रदेश',
            'template_name' => 'BorrowerPermanentProvince',
            'key' => 'b_p_province',
            'foreign_key' =>'province',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_p_district'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Permanent District',
            'name_np' => 'जिल्ला',
            'template_name' => 'BorrowerPermanentDistrict',
            'key' => 'b_p_district',
            'foreign_key' =>'district',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_p_localgovt'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Permanent LocalGovt',
            'name_np' => 'स्थानिय तह',
            'template_name' => 'BorrowerPermanentLocalGovt',
            'key' => 'b_p_localgovt',
            'foreign_key' =>'localgovt',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_p_ward'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Permanent Ward',
            'name_np' => 'वडा नं',
            'template_name' => 'BorrowerPermanentWard',
            'key' => 'b_p_ward',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_p_tole'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Permanent Tole',
            'name_np' => 'टोल',
            'template_name' => 'BorrowerPermanentTole',
            'key' => 'b_p_tole',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],


        'b_t_province'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Temporary Province',
            'name_np' => 'प्रदेश',
            'template_name' => 'BorrowerTemporaryProvince',
            'key' => 'b_t_province',
            'foreign_key' =>'province',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_t_district'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Temporary District',
            'name_np' => 'जिल्ला',
            'template_name' => 'BorrowerTemporaryDistrict',
            'key' => 'b_t_district',
            'foreign_key' =>'district',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_t_localgovt'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Temporary LocalGovt',
            'name_np' => 'स्थानिय तह',
            'template_name' => 'BorrowerTemporaryLocalGovt',
            'key' => 'b_t_localgovt',
            'foreign_key' =>'localgovt',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'b_t_ward'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Temporary Ward',
            'name_np' => 'वडा नं',
            'template_name' => 'BorrowerTemporaryWard',
            'key' => 'b_t_ward',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'b_t_tole'=>[
            'lang' => 'np',
            'name_en' => 'Borrower Temporary Tole',
            'name_np' => 'टोल',
            'template_name' => 'BorrowerTemporaryTole',
            'key' => 'b_t_tole',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'monthly_income'=>[
            'lang' => 'np',
            'name_en' => 'Monthly Income',
            'name_np' => 'मासिक आम्दानी',
            'template_name' => 'MonthlyIncome',
            'key' => 'monthly_income',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'monthly_expenses'=>[
            'lang' => 'np',
            'name_en' => 'Monthly Expenses',
            'name_np' => 'मासिक खर्च',
            'template_name' => 'MonthlyExpenses',
            'key' => 'monthly_expenses',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'monthly_saving'=>[
            'lang' => 'np',
            'name_en' => 'Monthly Saving',
            'name_np' => 'मासिक बचत',
            'template_name' => 'MonthlySaving',
            'key' => 'monthly_saving',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'citizenship_number'=>[
            'lang' => 'np',
            'name_en' => 'Citizenship Number',
            'name_np' => 'नागरिकता नं',
            'template_name' => 'CitizenshipNumber',
            'key' => 'citizenship_number',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'citizenship_issue_date'=>[
            'lang' => 'np',
            'name_en' => 'Citizenship Issue Date',
            'name_np' => 'नागरिकता जारी मिति',
            'template_name' => 'CitizenshipIssueDate',
            'key' => 'citizenship_issue_date',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'citizenship_issue_date_bs'=>[
            'lang' => 'np',
            'name_en' => 'Citizenship Issue Date(BS)',
            'name_np' => 'नागरिकता जारी मिति',
            'template_name' => 'CitizenshipIssueDateBS',
            'key' => 'citizenship_issue_date_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'citizenship_issue_district'=>[
            'lang' => 'np',
            'name_en' => 'Citizenship Issue District',
            'name_np' => 'नागरिकता जारी जिल्ला',
            'template_name' => 'CitizenshipIssueDistrict',
            'key' => 'citizenship_issue_district',
            'foreign_key' =>'district',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'citizenship_former_address'=>[
            'lang' => 'np',
            'name_en' => 'Citizenship Former Address',
            'name_np' => 'नागरिकता अनुसारको साबिक ठेगाना',
            'template_name' => 'CitizenshipFormerAddress',
            'key' => 'citizenship_former_address',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ], 

        'contact_number'=>[
            'lang' => 'np',
            'name_en' => 'Contact Number',
            'name_np' => 'सम्पर्क',
            'template_name' => 'ContactNumber',
            'key' => 'contact_number',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'loan_type'=>[
            'lang' => 'np',
            'name_en' => 'Collateral Type',
            'name_np' => 'धितो किसिम',
            'template_name' => 'CollateralType',
            'key' => 'loan_type',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'loan_apply_date'=>[
            'lang' => 'np',
            'name_en' => 'Loan Apply Date',
            'name_np' => 'ऋण आवेदन मिति',
            'template_name' => 'LoanApplyDate',
            'key' => 'loan_apply_date',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'loan_apply_date_bs'=>[
            'lang' => 'np',
            'name_en' => 'Loan Apply Date (BS)',
            'name_np' => 'ऋण आवेदन मिति',
            'template_name' => 'LoanApplyDateBS',
            'key' => 'loan_apply_date_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'loan_demand_amount'=>[
            'lang' => 'np',
            'name_en' => 'Loan Demand Amount',
            'name_np' => 'ऋण माग रकम',
            'template_name' => 'LoanDemandAmount',
            'key' => 'loan_demand_amount',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
    ],

    //Collateral Details
    'collateral_details' =>[
        'subscription_id'=>[
            'lang' => 'np',
            'name_en' => 'Subscription Id',
            'name_np' => 'सदस्यता नं',
            'template_name' => 'SubscriptionId',
            'key' => 'subscription_id',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'subscription_date'=>[
            'lang' => 'np',
            'name_en' => 'Subscription Date',
            'name_np' => 'सदस्य बनेको मिति',
            'template_name' => 'SubscriptionDate',
            'key' => 'subscription_date',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'subscription_date_bs'=>[
            'lang' => 'np',
            'name_en' => 'Subscription Date (BS)',
            'name_np' => 'सदस्य बनेको मिति',
            'template_name' => 'SubscriptionDateBs',
            'key' => 'subscription_date_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
    ],
    //loan Details
    'loan_details' =>[
        'total_loan_amount'=>[
            'lang' => 'np',
            'name_en' => 'Total Loan Amount',
            'name_np' => 'स्वीकृत ऋण रकम',
            'template_name' => 'TotalLoanAmount',
            'key' => 'total_loan_amount',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'total_loan_amount_in_word'=>[
            'lang' => 'np',
            'name_en' => 'Toal Loan Amount in Word',
            'name_np' => 'स्वीकृत ऋण रकम अक्षरुपि',
            'template_name' => 'TotalLoanAmountInWord',
            'key' => 'total_loan_amount_in_word',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'loan_title'=>[
            'lang' => 'np',
            'name_en' => 'Loan title',
            'name_np' => 'ऋण शिर्षक',
            'template_name' => 'Loantitle',
            'key' => 'loan_title',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],      
    ],
    //guarantor 1
    'guarantor_details' => [
        'guarantor1_name'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Name',
            'name_np' => 'धनजमानीको नाम',
            'template_name' => 'Guarantor1Name',
            'key' => 'guarantor1_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'guarantor1_father_name'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Father Name',
            'name_np' => 'बाबु/पतिको नाम',
            'template_name' => 'Guarantor1FatherName',
            'key' => 'guarantor1_father_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'guarantor1_grand_father_name'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Grand Father Name',
            'name_np' => 'बाजे/ससुराको नाम',
            'template_name' => 'Guarantor1GrandFatherName',
            'key' => 'guarantor1_grand_father_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'guarantor1_spouse_name'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Spouse Name',
            'name_np' => 'श्रीमान / श्रीमती नाम',
            'template_name' => 'Guarantor1SpouseName',
            'key' => 'guarantor1_spouse_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
        'guarantor1_relation'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Relation',
            'name_np' => 'ऋण लिनेसँगको नाता',
            'template_name' => 'Guarantor1Relation',
            'key' => 'guarantor1_relation',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.relations',
            'required' => true,
            'required_if'=> false,
        ],
        'guarantor1_subscription_id'=>[
            'lang' => 'np',
            'name_en' => 'Guarantor1 Subscription Id',
            'name_np' => 'सदस्यता नं',
            'template_name' => 'Guarantor1SubscriptionId',
            'key' => 'guarantor1_subscription_id',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
    ],
    'sanchi_details' => [
        //sachi1
    
        'sanchi1_name'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Name',
            'name_np' => 'साक्षीको नाम',
            'template_name' => 'Sanchi1Name',
            'key' => 'sanchi1_name',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'sanchi1_age'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Age',
            'name_np' => 'उमेर',
            'template_name' => 'Sanchi1Age',
            'key' => 'sanchi1_age',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'sanchi1_province'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Permanent Province',
            'name_np' => 'प्रदेश',
            'template_name' => 'Sanchi1PermanentProvince',
            'key' => 'sanchi1_province',
            'foreign_key' =>'province',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'sanchi1_district'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Permanent District',
            'name_np' => 'जिल्ला',
            'template_name' => 'Sanchi1PermanentDistrict',
            'key' => 'sanchi1_district',
            'foreign_key' =>'district',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'sanchi1_localgovt'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Permanent LocalGovt',
            'name_np' => 'स्थानिय तह',
            'template_name' => 'Sanchi1PermanentLocalGovt',
            'key' => 'sanchi1_localgovt',
            'foreign_key' =>'localgovt',
            'type' => 'number',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'sanchi1_ward'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Permanent Ward',
            'name_np' => 'वडा नं',
            'template_name' => 'Sanchi1PermanentWard',
            'key' => 'sanchi1_ward',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

        'sanchi1_tole'=>[
            'lang' => 'np',
            'name_en' => 'Sanchi1 Permanent Tole',
            'name_np' => 'टोल',
            'template_name' => 'Sanchi1PermanentTole',
            'key' => 'sanchi1_tole',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],

    ],
    'other_details' => [
    
    ]
];
