<?php
return [ 
    'taketa_patras'=>
    [
        'capital'=>[
            'lang' => 'np',
            'name_en' => 'Remaining Capital',
            'name_np' => 'साँवा वाँकी ',
            'template_name' => 'RemainingCapital',
            'key' => 'capital',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'interest'=>[
            'lang' => 'np',
            'name_en' => 'Remaining Interest',
            'name_np' => 'व्याज वाँकी',
            'template_name' => 'RemainingInterest',
            'key' => 'interest',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'other'=>[
            'lang' => 'np',
            'name_en' => 'Other',
            'name_np' => 'अन्य',
            'template_name' => 'other',
            'key' => 'other',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'total'=>[
            'lang' => 'np',
            'name_en' => 'Remaining Total',
            'name_np' => 'जम्मा वाँकी',
            'template_name' => 'RemainingTotal',
            'key' => 'total',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => false,
            'required_if'=> false,
        ],
        'letter_type'=>[
            'lang' => 'np',
            'name_en' => 'Letter Type',
            'name_np' => 'पत्र कसिम',
            'template_name' => 'LetterType',
            'key' => 'letter_type',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => 'custom.letter_type',
            'required' => true,
            'required_if'=> false,
        ],
        'last_installment_date'=>[
            'lang' => 'np',
            'name_en' => 'Last Installment Submission Date',
            'name_np' => 'अन्तिम किस्ता भुक्तानी मिति',
            'template_name' => 'LastInstallmentSubmissionDate',
            'key' => 'last_installment_date',
            'foreign_key' =>false,
            'type' => 'datetime',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
        'last_installment_date_bs'=>[
            'lang' => 'np',
            'name_en' => 'Last Installment Submission Date(BS)',
            'name_np' => 'अन्तिम किस्ता भुक्तानी मिति',
            'template_name' => 'LastInstallmentSubmissionDateBS',
            'key' => 'last_installment_date_bs',
            'foreign_key' =>false,
            'type' => 'string',
            'config' => false,
            'required' => true,
            'required_if'=> false,
        ],
    ],
];